# Generated by Django 6.0.1 on 2026-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_destination_post_location_postimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
